version: "3.5"
services:
  web-tik:
    image: dockerhub.uns.ac.id:5000/php73:latest
    ports:
      - 83:80
    volumes:
      - ./:/app/
      - ./deploy/docker/:/etc/apache2/sites-enabled/
      - ./deploy/docker/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      uns:

networks:
  uns:
    name: uns
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
